name: RECA Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ghcr.io/cirruslabs/macos-runner:sonoma
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Run RECA Build (Xcode 16)
      uses: RECAAI/github-action/reca-build@main
      with:
        xcode-version: '16'
        platforms: '["all"]'
        configurations: '["debug"]'
